name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
      - 'environment.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
      - 'environment.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Create mock model file for testing
        run: echo "mock model" > /tmp/model.gguf
      - name: Run tests
        run: pytest -v